# Generated by Django 4.2.5 on 2023-12-20 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
